//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Server.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comp
    {
        public Comp()
        {
            this.Menu_Order = new HashSet<Menu_Order>();
        }
    
        public int idComp { get; set; }
        public string Text { get; set; }
        public decimal Price { get; set; }
        public int idEmployee { get; set; }
        public string Coupon_Code { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
    
        public virtual ICollection<Menu_Order> Menu_Order { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
