//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Server.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Comps = new HashSet<Comp>();
            this.Orders = new HashSet<Order>();
            this.Tables = new HashSet<Table>();
        }
    
        public int idEmployee { get; set; }
        public string Name { get; set; }
        public int idEmployee_Type { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Comp> Comps { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Table> Tables { get; set; }
        public virtual Employee_Type Employee_Type { get; set; }
    }
}
