//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Server.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Item
    {
        public Menu_Item()
        {
            this.Menu_Order = new HashSet<Menu_Order>();
        }
    
        public int idMenu_Item { get; set; }
        public int Calories { get; set; }
        public decimal Price { get; set; }
        public byte[] Picture { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long Category_idCategory { get; set; }
        public int Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Menu_Order> Menu_Order { get; set; }
    }
}
