//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Server.ServiceModel.Service.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Menu_Order = new HashSet<Menu_Order>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int idOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Table_idTable { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Tip { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> idServer { get; set; }
        public Nullable<int> Customer_idCustomer { get; set; }
        public Nullable<int> idChef { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Menu_Order> Menu_Order { get; set; }
        public virtual Table Table { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
