//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Server.BL
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class CustomerBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime birthdayField;

        private string emailField;

        private int idCustomerField;

        private string nameField;

        private string phoneField;

        private int pointsField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer
        {
            get
            {
                return this.idCustomerField;
            }
            set
            {
                this.idCustomerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class EmployeeBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int employeeTypeField;

        private int idEmployeeField;

        private string nameField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int employeeType
        {
            get
            {
                return this.employeeTypeField;
            }
            set
            {
                this.employeeTypeField = value;
            }
        }

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int employeeType
        {
            get
            {
                return this.employeeTypeField;
            }
            set
            {
                this.employeeTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmployee
        {
            get
            {
                return this.idEmployeeField;
            }
            set
            {
                this.idEmployeeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class OrderBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime dateField;

        private int idCustomerField;

        private int idOrderField;

        private int idServerField;

        private int idTableField;

        private double subTotalField;

        private double taxField;

        private double tipField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer
        {
            get
            {
                return this.idCustomerField;
            }
            set
            {
                this.idCustomerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOrder
        {
            get
            {
                return this.idOrderField;
            }
            set
            {
                this.idOrderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idServer
        {
            get
            {
                return this.idServerField;
            }
            set
            {
                this.idServerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTable
        {
            get
            {
                return this.idTableField;
            }
            set
            {
                this.idTableField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double subTotal
        {
            get
            {
                return this.subTotalField;
            }
            set
            {
                this.subTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double tip
        {
            get
            {
                return this.tipField;
            }
            set
            {
                this.tipField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuOrderBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class MenuOrderBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string RequestField;

        private int idCompField;

        private int idChefField;

        private int idCustomerField;

        private int idMenuItemField;

        private int idMenuOrderField;

        private int idOrderField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComp
        {
            get
            {
                return this.idCompField;
            }
            set
            {
                this.idCompField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer
        {
            get
            {
                return this.idCustomerField;
            }
            set
            {
                this.idCustomerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenuItem
        {
            get
            {
                return this.idMenuItemField;
            }
            set
            {
                this.idMenuItemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenuOrder
        {
            get
            {
                return this.idMenuOrderField;
            }
            set
            {
                this.idMenuOrderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOrder
        {
            get
            {
                return this.idOrderField;
            }
            set
            {
                this.idOrderField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class CategoryBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int CategoryIDField;

        private string NameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItemBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class MenuItemBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int caloriesField;

        private string categoryField;

        private string descriptionField;

        private int idMenuItemField;

        private string nameField;

        private double priceField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int calories
        {
            get
            {
                return this.caloriesField;
            }
            set
            {
                this.caloriesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenuItem
        {
            get
            {
                return this.idMenuItemField;
            }
            set
            {
                this.idMenuItemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class CompBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string couponCodeField;

        private System.DateTime expirationDateField;

        private int idCompField;

        private int idEmployeeField;

        private double priceField;

        private string reasonField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string couponCode
        {
            get
            {
                return this.couponCodeField;
            }
            set
            {
                this.couponCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComp
        {
            get
            {
                return this.idCompField;
            }
            set
            {
                this.idCompField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmployee
        {
            get
            {
                return this.idEmployeeField;
            }
            set
            {
                this.idEmployeeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class PaymentBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private double amountField;

        private int idCustomerField;

        private int idOrderField;

        private int idPaymentField;

        private string methodField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer
        {
            get
            {
                return this.idCustomerField;
            }
            set
            {
                this.idCustomerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOrder
        {
            get
            {
                return this.idOrderField;
            }
            set
            {
                this.idOrderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPayment
        {
            get
            {
                return this.idPaymentField;
            }
            set
            {
                this.idPaymentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://RMS.Server.ServiceModel.Service.BL", ConfigurationName="IRestaurantService")]
public interface IRestaurantService
{

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategoryRespon" +
        "se")]
    int InsertCategory(string name);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategoryRespon" +
        "se")]
    System.Threading.Tasks.Task<int> InsertCategoryAsync(string name);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryNameRespo" +
        "nse")]
    string GetCategoryName(int CategoryID);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryNameRespo" +
        "nse")]
    System.Threading.Tasks.Task<string> GetCategoryNameAsync(int CategoryID);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryNameRe" +
        "sponse")]
    bool UpdateCategoryName(int idCategory, string name);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryNameRe" +
        "sponse")]
    System.Threading.Tasks.Task<bool> UpdateCategoryNameAsync(int idCategory, string name);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategoryRespon" +
        "se")]
    bool DeleteCategory(int idCategory);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategoryRespon" +
        "se")]
    System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int idCategory);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomer", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomerRespon" +
        "se")]
    int InsertCustomer(string name, System.DateTime bday, string phone, string email);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomer", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomerRespon" +
        "se")]
    System.Threading.Tasks.Task<int> InsertCustomerAsync(string name, System.DateTime bday, string phone, string email);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployee", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployeeRespon" +
        "se")]
    int InsertEmployee(int employeeCategoryId, string name, string password);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployee", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployeeRespon" +
        "se")]
    System.Threading.Tasks.Task<int> InsertEmployeeAsync(int employeeCategoryId, string name, string password);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateEmployee", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateEmployeeRespon" +
        "se")]
    bool UpdateEmployee(RMS.Server.BL.EmployeeBL employee);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateEmployee", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateEmployeeRespon" +
        "se")]
    System.Threading.Tasks.Task<bool> UpdateEmployeeAsync(RMS.Server.BL.EmployeeBL employee);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookupR" +
        "esponse")]
    RMS.Server.BL.CustomerBL CustomerPhoneLookup(string phone);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookupR" +
        "esponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerPhoneLookupAsync(string phone);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookupR" +
        "esponse")]
    RMS.Server.BL.CustomerBL CustomerEmailLookup(string email);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookupR" +
        "esponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerEmailLookupAsync(string email);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookupRespon" +
        "se")]
    RMS.Server.BL.EmployeeBL EmployeeLookup(string name);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookupRespon" +
        "se")]
    System.Threading.Tasks.Task<RMS.Server.BL.EmployeeBL> EmployeeLookupAsync(string name);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderResponse")]
    int SubmitOrder(int customerid, int tableId);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderResponse")]
    System.Threading.Tasks.Task<int> SubmitOrderAsync(RMS.Server.BL.OrderBL new_order);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItemRespo" +
        "nse")]
    int SubmitOrderItem(RMS.Server.BL.MenuOrderBL Item);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItemRespo" +
        "nse")]
    System.Threading.Tasks.Task<int> SubmitOrderItemAsync(RMS.Server.BL.MenuOrderBL Item);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderRespons" +
        "e")]
    RMS.Server.BL.OrderBL RetrieveOrder(int idTable);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderRespons" +
        "e")]
    System.Threading.Tasks.Task<RMS.Server.BL.OrderBL> RetrieveOrderAsync(int idTable);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItems", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItemsRe" +
        "sponse")]
    RMS.Server.BL.MenuOrderBL[] RetrieveOrderItems(int Order);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItems", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItemsRe" +
        "sponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> RetrieveOrderItemsAsync(int Order);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItemResponse")]
    bool ClaimItem(int Item);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItemResponse")]
    System.Threading.Tasks.Task<bool> ClaimItemAsync(int Item);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItemResponse")]
    bool ReadyItem(int Item);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItemResponse")]
    System.Threading.Tasks.Task<bool> ReadyItemAsync(int Item);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategoryRespon" +
        "se")]
    RMS.Server.BL.CategoryBL[] GetAllCategory();

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategoryRespon" +
        "se")]
    System.Threading.Tasks.Task<RMS.Server.BL.CategoryBL[]> GetAllCategoryAsync();

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieve", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieveResp" +
        "onse")]
    RMS.Server.BL.MenuItemBL[] CategoryRetrieve(int Category);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieve", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieveResp" +
        "onse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> CategoryRetrieveAsync(int Category);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookupResponse")]
    double PriceLookup(int idItem);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookupResponse")]
    System.Threading.Tasks.Task<double> PriceLookupAsync(int idItem);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookupResponse")]
    RMS.Server.BL.MenuItemBL ItemLookup(int idItem);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookupResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL> ItemLookupAsync(int idItem);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItemResponse" +
        "")]
    bool ActivateItem(RMS.Server.BL.MenuItemBL alive);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItemResponse" +
        "")]
    System.Threading.Tasks.Task<bool> ActivateItemAsync(RMS.Server.BL.MenuItemBL alive);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItemRespon" +
        "se")]
    bool DeactivateItem(RMS.Server.BL.MenuItemBL dead);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItemRespon" +
        "se")]
    System.Threading.Tasks.Task<bool> DeactivateItemAsync(RMS.Server.BL.MenuItemBL dead);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookupResponse")]
    RMS.Server.BL.CompBL CompLookup(int idMenuOrder);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookupResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.CompBL> CompLookupAsync(int idMenuOrder);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItemResponse")]
    int CompItem(RMS.Server.BL.CompBL newComp);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItemResponse")]
    System.Threading.Tasks.Task<int> CompItemAsync(RMS.Server.BL.CompBL newComp);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateComp", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateCompResponse")]
    bool updateComp(int idMenuOrder, int idComp);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateComp", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateCompResponse")]
    System.Threading.Tasks.Task<bool> updateCompAsync(int idMenuOrder, int idComp);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Payment", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PaymentResponse")]
    int Payment(int idOrder, string method, double amount);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Payment", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PaymentResponse")]
    System.Threading.Tasks.Task<int> PaymentAsync(int idOrder, string method, double amount);

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReportRespon" +
        "se")]
    RMS.Server.BL.CompBL[] DiscountReport();

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReportRespon" +
        "se")]
    System.Threading.Tasks.Task<RMS.Server.BL.CompBL[]> DiscountReportAsync();

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3Report", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3ReportResponse")]
    RMS.Server.BL.MenuItemBL[] Top3Report();

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3Report", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3ReportResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> Top3ReportAsync();

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReportRespons" +
        "e")]
    RMS.Server.BL.PaymentBL[] RevenueReport();

    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReportRespons" +
        "e")]
    System.Threading.Tasks.Task<RMS.Server.BL.PaymentBL[]> RevenueReportAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRestaurantServiceChannel : IRestaurantService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RestaurantServiceClient : System.ServiceModel.ClientBase<IRestaurantService>, IRestaurantService
{

    public RestaurantServiceClient()
    {
    }

    public RestaurantServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public RestaurantServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public RestaurantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public RestaurantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public int InsertCategory(string name)
    {
        return base.Channel.InsertCategory(name);
    }

    public System.Threading.Tasks.Task<int> InsertCategoryAsync(string name)
    {
        return base.Channel.InsertCategoryAsync(name);
    }

    public string GetCategoryName(int CategoryID)
    {
        return base.Channel.GetCategoryName(CategoryID);
    }

    public System.Threading.Tasks.Task<string> GetCategoryNameAsync(int CategoryID)
    {
        return base.Channel.GetCategoryNameAsync(CategoryID);
    }

    public bool UpdateCategoryName(int idCategory, string name)
    {
        return base.Channel.UpdateCategoryName(idCategory, name);
    }

    public System.Threading.Tasks.Task<bool> UpdateCategoryNameAsync(int idCategory, string name)
    {
        return base.Channel.UpdateCategoryNameAsync(idCategory, name);
    }

    public bool DeleteCategory(int idCategory)
    {
        return base.Channel.DeleteCategory(idCategory);
    }

    public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int idCategory)
    {
        return base.Channel.DeleteCategoryAsync(idCategory);
    }

    public int InsertCustomer(string name, System.DateTime bday, string phone, string email)
    {
        return base.Channel.InsertCustomer(name, bday, phone, email);
    }

    public System.Threading.Tasks.Task<int> InsertCustomerAsync(string name, System.DateTime bday, string phone, string email)
    {
        return base.Channel.InsertCustomerAsync(name, bday, phone, email);
    }

    public int InsertEmployee(int employeeCategoryId, string name, string password)
    {
        return base.Channel.InsertEmployee(employeeCategoryId, name, password);
    }

    public System.Threading.Tasks.Task<int> InsertEmployeeAsync(int employeeCategoryId, string name, string password)
    {
        return base.Channel.InsertEmployeeAsync(employeeCategoryId, name, password);
    }

    public bool UpdateEmployee(RMS.Server.BL.EmployeeBL employee)
    {
        return base.Channel.UpdateEmployee(employee);
    }

    public System.Threading.Tasks.Task<bool> UpdateEmployeeAsync(RMS.Server.BL.EmployeeBL employee)
    {
        return base.Channel.UpdateEmployeeAsync(employee);
    }

    public RMS.Server.BL.CustomerBL CustomerPhoneLookup(string phone)
    {
        return base.Channel.CustomerPhoneLookup(phone);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerPhoneLookupAsync(string phone)
    {
        return base.Channel.CustomerPhoneLookupAsync(phone);
    }

    public RMS.Server.BL.CustomerBL CustomerEmailLookup(string email)
    {
        return base.Channel.CustomerEmailLookup(email);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerEmailLookupAsync(string email)
    {
        return base.Channel.CustomerEmailLookupAsync(email);
    }

    public RMS.Server.BL.EmployeeBL EmployeeLookup(string name)
    {
        return base.Channel.EmployeeLookup(name);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.EmployeeBL> EmployeeLookupAsync(string name)
    {
        return base.Channel.EmployeeLookupAsync(name);
    }

    public int SubmitOrder(int customerid, int tableId)
    {
        return base.Channel.SubmitOrder(customerid, tableId);
    }

    public System.Threading.Tasks.Task<int> SubmitOrderAsync(int customerid, int tableId)
    {
        return base.Channel.SubmitOrderAsync(customerid, tableId);
    }

    public int SubmitOrderItem(RMS.Server.BL.MenuOrderBL Item)
    {
        return base.Channel.SubmitOrderItem(Item);
    }

    public System.Threading.Tasks.Task<int> SubmitOrderItemAsync(RMS.Server.BL.MenuOrderBL Item)
    {
        return base.Channel.SubmitOrderItemAsync(Item);
    }

    public RMS.Server.BL.OrderBL RetrieveOrder(int idTable)
    {
        return base.Channel.RetrieveOrder(idTable);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.OrderBL> RetrieveOrderAsync(int idTable)
    {
        return base.Channel.RetrieveOrderAsync(idTable);
    }

    public RMS.Server.BL.MenuOrderBL[] RetrieveOrderItems(int Order)
    {
        return base.Channel.RetrieveOrderItems(Order);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> RetrieveOrderItemsAsync(int Order)
    {
        return base.Channel.RetrieveOrderItemsAsync(Order);
    }

    public bool ClaimItem(int Item)
    {
        return base.Channel.ClaimItem(Item);
    }

    public System.Threading.Tasks.Task<bool> ClaimItemAsync(int Item)
    {
        return base.Channel.ClaimItemAsync(Item);
    }

    public bool ReadyItem(int Item)
    {
        return base.Channel.ReadyItem(Item);
    }

    public System.Threading.Tasks.Task<bool> ReadyItemAsync(int Item)
    {
        return base.Channel.ReadyItemAsync(Item);
    }

    public RMS.Server.BL.CategoryBL[] GetAllCategory()
    {
        return base.Channel.GetAllCategory();
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.CategoryBL[]> GetAllCategoryAsync()
    {
        return base.Channel.GetAllCategoryAsync();
    }

    public RMS.Server.BL.MenuItemBL[] GetAllMenuItems(int idCategory)
    {
        return base.Channel.GetAllMenuItems(idCategory);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> GetAllMenuItemsAsync(int idCategory)
    {
        return base.Channel.GetAllMenuItemsAsync(idCategory);
    }

    public double PriceLookup(int idItem)
    {
        return base.Channel.PriceLookup(idItem);
    }

    public System.Threading.Tasks.Task<double> PriceLookupAsync(int idItem)
    {
        return base.Channel.PriceLookupAsync(idItem);
    }

    public RMS.Server.BL.MenuItemBL ItemLookup(int idItem)
    {
        return base.Channel.ItemLookup(idItem);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL> ItemLookupAsync(int idItem)
    {
        return base.Channel.ItemLookupAsync(idItem);
    }

    public bool ActivateItem(RMS.Server.BL.MenuItemBL alive)
    {
        return base.Channel.ActivateItem(alive);
    }

    public System.Threading.Tasks.Task<bool> ActivateItemAsync(RMS.Server.BL.MenuItemBL alive)
    {
        return base.Channel.ActivateItemAsync(alive);
    }

    public bool DeactivateItem(RMS.Server.BL.MenuItemBL dead)
    {
        return base.Channel.DeactivateItem(dead);
    }

    public System.Threading.Tasks.Task<bool> DeactivateItemAsync(RMS.Server.BL.MenuItemBL dead)
    {
        return base.Channel.DeactivateItemAsync(dead);
    }

    public RMS.Server.BL.CompBL CompLookup(int idMenuOrder)
    {
        return base.Channel.CompLookup(idMenuOrder);
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.CompBL> CompLookupAsync(int idMenuOrder)
    {
        return base.Channel.CompLookupAsync(idMenuOrder);
    }

    public int CompItem(RMS.Server.BL.CompBL newComp)
    {
        return base.Channel.CompItem(newComp);
    }

    public System.Threading.Tasks.Task<int> CompItemAsync(RMS.Server.BL.CompBL newComp)
    {
        return base.Channel.CompItemAsync(newComp);
    }

    public bool updateComp(int idMenuOrder, int idComp)
    {
        return base.Channel.updateComp(idMenuOrder, idComp);
    }

    public System.Threading.Tasks.Task<bool> updateCompAsync(int idMenuOrder, int idComp)
    {
        return base.Channel.updateCompAsync(idMenuOrder, idComp);
    }

    public int Payment(int idOrder, string method, double amount)
    {
        return base.Channel.Payment(idOrder, method, amount);
    }

    public System.Threading.Tasks.Task<int> PaymentAsync(int idOrder, string method, double amount)
    {
        return base.Channel.PaymentAsync(idOrder, method, amount);
    }

    public RMS.Server.BL.CompBL[] DiscountReport()
    {
        return base.Channel.DiscountReport();
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.CompBL[]> DiscountReportAsync()
    {
        return base.Channel.DiscountReportAsync();
    }

    public RMS.Server.BL.MenuItemBL[] Top3Report()
    {
        return base.Channel.Top3Report();
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> Top3ReportAsync()
    {
        return base.Channel.Top3ReportAsync();
    }

    public RMS.Server.BL.PaymentBL[] RevenueReport()
    {
        return base.Channel.RevenueReport();
    }

    public System.Threading.Tasks.Task<RMS.Server.BL.PaymentBL[]> RevenueReportAsync()
    {
        return base.Channel.RevenueReportAsync();
    }
}
