//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMS.Server.BL
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class CustomerBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime birthdayField;
        
        private string emailField;
        
        private int idCustomerField;
        
        private string nameField;
        
        private string phoneField;
        
        private int pointsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer
        {
            get
            {
                return this.idCustomerField;
            }
            set
            {
                this.idCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int points
        {
            get
            {
                return this.pointsField;
            }
            set
            {
                this.pointsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class EmployeeBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int employeeTypeField;
        
        private int idEmployeeField;
        
        private string nameField;
        
        private string passwordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int employeeType
        {
            get
            {
                return this.employeeTypeField;
            }
            set
            {
                this.employeeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmployee
        {
            get
            {
                return this.idEmployeeField;
            }
            set
            {
                this.idEmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class OrderBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StatusField;
        
        private System.DateTime dateField;
        
        private int idCustomerField;
        
        private int idOrderField;
        
        private int idServerField;
        
        private int idTableField;
        
        private decimal subTotalField;
        
        private decimal taxField;
        
        private decimal tipField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer
        {
            get
            {
                return this.idCustomerField;
            }
            set
            {
                this.idCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOrder
        {
            get
            {
                return this.idOrderField;
            }
            set
            {
                this.idOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idServer
        {
            get
            {
                return this.idServerField;
            }
            set
            {
                this.idServerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTable
        {
            get
            {
                return this.idTableField;
            }
            set
            {
                this.idTableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal subTotal
        {
            get
            {
                return this.subTotalField;
            }
            set
            {
                this.subTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal tax
        {
            get
            {
                return this.taxField;
            }
            set
            {
                this.taxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal tip
        {
            get
            {
                return this.tipField;
            }
            set
            {
                this.tipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuOrderBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class MenuOrderBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ItemNameField;
        
        private decimal PriceField;
        
        private string RequestField;
        
        private string StatusField;
        
        private int idCategoryField;
        
        private int idCompField;
        
        private int idMenuItemField;
        
        private int idMenuOrderField;
        
        private int idOrderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName
        {
            get
            {
                return this.ItemNameField;
            }
            set
            {
                this.ItemNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Request
        {
            get
            {
                return this.RequestField;
            }
            set
            {
                this.RequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategory
        {
            get
            {
                return this.idCategoryField;
            }
            set
            {
                this.idCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComp
        {
            get
            {
                return this.idCompField;
            }
            set
            {
                this.idCompField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenuItem
        {
            get
            {
                return this.idMenuItemField;
            }
            set
            {
                this.idMenuItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenuOrder
        {
            get
            {
                return this.idMenuOrderField;
            }
            set
            {
                this.idMenuOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOrder
        {
            get
            {
                return this.idOrderField;
            }
            set
            {
                this.idOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class CategoryBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CategoryIDField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItemBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class MenuItemBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int caloriesField;
        
        private string categoryField;
        
        private string descriptionField;
        
        private int idMenuItemField;
        
        private string nameField;
        
        private decimal priceField;
        
        private int statusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int calories
        {
            get
            {
                return this.caloriesField;
            }
            set
            {
                this.caloriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMenuItem
        {
            get
            {
                return this.idMenuItemField;
            }
            set
            {
                this.idMenuItemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class CompBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string couponCodeField;
        
        private System.DateTime expirationDateField;
        
        private int idCompField;
        
        private int idEmployeeField;
        
        private decimal priceField;
        
        private string reasonField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string couponCode
        {
            get
            {
                return this.couponCodeField;
            }
            set
            {
                this.couponCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComp
        {
            get
            {
                return this.idCompField;
            }
            set
            {
                this.idCompField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEmployee
        {
            get
            {
                return this.idEmployeeField;
            }
            set
            {
                this.idEmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class PaymentBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal amountField;
        
        private int idCustomerField;
        
        private int idOrderField;
        
        private int idPaymentField;
        
        private string methodField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCustomer
        {
            get
            {
                return this.idCustomerField;
            }
            set
            {
                this.idCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOrder
        {
            get
            {
                return this.idOrderField;
            }
            set
            {
                this.idOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPayment
        {
            get
            {
                return this.idPaymentField;
            }
            set
            {
                this.idPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string method
        {
            get
            {
                return this.methodField;
            }
            set
            {
                this.methodField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodReportBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class FoodReportBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int countField;
        
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableBL", Namespace="http://schemas.datacontract.org/2004/07/RMS.Server.BL")]
    public partial class TableBL : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idServerField;
        
        private int idTableField;
        
        private string locationField;
        
        private string requestField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idServer
        {
            get
            {
                return this.idServerField;
            }
            set
            {
                this.idServerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTable
        {
            get
            {
                return this.idTableField;
            }
            set
            {
                this.idTableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://RMS.Server.ServiceModel.Service.BL", ConfigurationName="IRestaurantService")]
public interface IRestaurantService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategoryRespon" +
        "se")]
    int InsertCategory(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCategoryRespon" +
        "se")]
    System.Threading.Tasks.Task<int> InsertCategoryAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryNameRespo" +
        "nse")]
    string GetCategoryName(int CategoryID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetCategoryNameRespo" +
        "nse")]
    System.Threading.Tasks.Task<string> GetCategoryNameAsync(int CategoryID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryNameRe" +
        "sponse")]
    bool UpdateCategoryName(int idCategory, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryName", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateCategoryNameRe" +
        "sponse")]
    System.Threading.Tasks.Task<bool> UpdateCategoryNameAsync(int idCategory, string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategoryRespon" +
        "se")]
    bool DeleteCategory(int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeleteCategoryRespon" +
        "se")]
    System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomer", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomerRespon" +
        "se")]
    int InsertCustomer(string name, System.DateTime bday, string phone, string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomer", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertCustomerRespon" +
        "se")]
    System.Threading.Tasks.Task<int> InsertCustomerAsync(string name, System.DateTime bday, string phone, string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployee", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployeeRespon" +
        "se")]
    int InsertEmployee(string name, string password, string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployee", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/InsertEmployeeRespon" +
        "se")]
    System.Threading.Tasks.Task<int> InsertEmployeeAsync(string name, string password, string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeReset", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeResetRespons" +
        "e")]
    bool EmployeeReset(string name, string new_password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeReset", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeResetRespons" +
        "e")]
    System.Threading.Tasks.Task<bool> EmployeeResetAsync(string name, string new_password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerReset", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerResetRespons" +
        "e")]
    bool CustomerReset(string name, string new_phone);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerReset", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerResetRespons" +
        "e")]
    System.Threading.Tasks.Task<bool> CustomerResetAsync(string name, string new_phone);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookupR" +
        "esponse")]
    RMS.Server.BL.CustomerBL CustomerPhoneLookup(string phone);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerPhoneLookupR" +
        "esponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerPhoneLookupAsync(string phone);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookupR" +
        "esponse")]
    RMS.Server.BL.CustomerBL CustomerEmailLookup(string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CustomerEmailLookupR" +
        "esponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerEmailLookupAsync(string email);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookupRespon" +
        "se")]
    RMS.Server.BL.EmployeeBL EmployeeLookup(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/EmployeeLookupRespon" +
        "se")]
    System.Threading.Tasks.Task<RMS.Server.BL.EmployeeBL> EmployeeLookupAsync(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/OrderCount", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/OrderCountResponse")]
    int OrderCount();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/OrderCount", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/OrderCountResponse")]
    System.Threading.Tasks.Task<int> OrderCountAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderStatus", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderStatusRes" +
        "ponse")]
    bool UpdateOrderStatus(int idOrder, int status);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderStatus", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderStatusRes" +
        "ponse")]
    System.Threading.Tasks.Task<bool> UpdateOrderStatusAsync(int idOrder, int status);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderTip", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderTipRespon" +
        "se")]
    bool UpdateOrderTip(int idOrder, decimal tip);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderTip", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderTipRespon" +
        "se")]
    System.Threading.Tasks.Task<bool> UpdateOrderTipAsync(int idOrder, decimal tip);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderResponse")]
    int SubmitOrder(RMS.Server.BL.OrderBL new_order);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderResponse")]
    System.Threading.Tasks.Task<int> SubmitOrderAsync(RMS.Server.BL.OrderBL new_order);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItemRespo" +
        "nse")]
    int SubmitOrderItem(RMS.Server.BL.MenuOrderBL Item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/SubmitOrderItemRespo" +
        "nse")]
    System.Threading.Tasks.Task<int> SubmitOrderItemAsync(RMS.Server.BL.MenuOrderBL Item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderRespons" +
        "e")]
    RMS.Server.BL.OrderBL RetrieveOrder(int idTable);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderRespons" +
        "e")]
    System.Threading.Tasks.Task<RMS.Server.BL.OrderBL> RetrieveOrderAsync(int idTable);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItems", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItemsRe" +
        "sponse")]
    RMS.Server.BL.MenuOrderBL[] RetrieveOrderItems(int Order);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItems", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RetrieveOrderItemsRe" +
        "sponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> RetrieveOrderItemsAsync(int Order);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItemResponse")]
    bool ClaimItem(int Item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ClaimItemResponse")]
    System.Threading.Tasks.Task<bool> ClaimItemAsync(int Item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetOrderByTableId", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetOrderByTableIdRes" +
        "ponse")]
    RMS.Server.BL.OrderBL[] GetOrderByTableId(int tableId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetOrderByTableId", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetOrderByTableIdRes" +
        "ponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetOrderByTableIdAsync(int tableId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableOrder" +
        "sForKitchen", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableOrder" +
        "sForKitchenResponse")]
    RMS.Server.BL.OrderBL[] GetAllAvailableOrdersForKitchen();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableOrder" +
        "sForKitchen", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableOrder" +
        "sForKitchenResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetAllAvailableOrdersForKitchenAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllOrderTableStat" +
        "us", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllOrderTableStat" +
        "usResponse")]
    RMS.Server.BL.OrderBL[] GetAllOrderTableStatus();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllOrderTableStat" +
        "us", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllOrderTableStat" +
        "usResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetAllOrderTableStatusAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForOr" +
        "der", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForOr" +
        "derResponse")]
    RMS.Server.BL.MenuOrderBL[] GetAllMenuOrderForOrder(int orderId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForOr" +
        "der", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForOr" +
        "derResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> GetAllMenuOrderForOrderAsync(int orderId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForKi" +
        "tchen", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForKi" +
        "tchenResponse")]
    RMS.Server.BL.MenuOrderBL[] GetAllMenuOrderForKitchen(int orderId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForKi" +
        "tchen", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuOrderForKi" +
        "tchenResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> GetAllMenuOrderForKitchenAsync(int orderId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderMenuStatu" +
        "s", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderMenuStatu" +
        "sResponse")]
    bool UpdateOrderMenuStatus(int menuOrderId, string status);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderMenuStatu" +
        "s", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/UpdateOrderMenuStatu" +
        "sResponse")]
    System.Threading.Tasks.Task<bool> UpdateOrderMenuStatusAsync(int menuOrderId, string status);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItemResponse")]
    bool ReadyItem(int Item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ReadyItemResponse")]
    System.Threading.Tasks.Task<bool> ReadyItemAsync(int Item);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RequestAssistance", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RequestAssistanceRes" +
        "ponse")]
    bool RequestAssistance(int table, string AssistType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RequestAssistance", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RequestAssistanceRes" +
        "ponse")]
    System.Threading.Tasks.Task<bool> RequestAssistanceAsync(int table, string AssistType);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategoryRespon" +
        "se")]
    RMS.Server.BL.CategoryBL[] GetAllCategory();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategory", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllCategoryRespon" +
        "se")]
    System.Threading.Tasks.Task<RMS.Server.BL.CategoryBL[]> GetAllCategoryAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuItemRespon" +
        "se")]
    RMS.Server.BL.MenuItemBL[] GetAllMenuItem();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllMenuItemRespon" +
        "se")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> GetAllMenuItemAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieve", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieveResp" +
        "onse")]
    RMS.Server.BL.MenuItemBL[] CategoryRetrieve(int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieve", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CategoryRetrieveResp" +
        "onse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> CategoryRetrieveAsync(int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAvailableMenuItem" +
        "s", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAvailableMenuItem" +
        "sResponse")]
    RMS.Server.BL.MenuItemBL[] GetAvailableMenuItems(int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAvailableMenuItem" +
        "s", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAvailableMenuItem" +
        "sResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> GetAvailableMenuItemsAsync(int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookupResponse")]
    double PriceLookup(int idItem);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PriceLookupResponse")]
    System.Threading.Tasks.Task<double> PriceLookupAsync(int idItem);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookupResponse")]
    RMS.Server.BL.MenuItemBL ItemLookup(int idItem);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ItemLookupResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL> ItemLookupAsync(int idItem);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItemResponse" +
        "")]
    bool ActivateItem(RMS.Server.BL.MenuItemBL alive);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/ActivateItemResponse" +
        "")]
    System.Threading.Tasks.Task<bool> ActivateItemAsync(RMS.Server.BL.MenuItemBL alive);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItemRespon" +
        "se")]
    bool DeactivateItem(RMS.Server.BL.MenuItemBL dead);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DeactivateItemRespon" +
        "se")]
    System.Threading.Tasks.Task<bool> DeactivateItemAsync(RMS.Server.BL.MenuItemBL dead);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookupResponse")]
    RMS.Server.BL.CompBL CompLookup(int idMenuOrder);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookup", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompLookupResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.CompBL> CompLookupAsync(int idMenuOrder);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItemResponse")]
    int CompItem(RMS.Server.BL.CompBL newComp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItem", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/CompItemResponse")]
    System.Threading.Tasks.Task<int> CompItemAsync(RMS.Server.BL.CompBL newComp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateComp", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateCompResponse")]
    bool updateComp(int idMenuOrder, int idComp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateComp", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/updateCompResponse")]
    System.Threading.Tasks.Task<bool> updateCompAsync(int idMenuOrder, int idComp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Payment", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PaymentResponse")]
    int Payment(int idOrder, string method, double amount, int userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Payment", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/PaymentResponse")]
    System.Threading.Tasks.Task<int> PaymentAsync(int idOrder, string method, double amount, int userID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReportRespon" +
        "se")]
    RMS.Server.BL.CompBL[] DiscountReport();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/DiscountReportRespon" +
        "se")]
    System.Threading.Tasks.Task<RMS.Server.BL.CompBL[]> DiscountReportAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3Report", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3ReportResponse")]
    RMS.Server.BL.MenuItemBL[] Top3Report();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3Report", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/Top3ReportResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> Top3ReportAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReportRespons" +
        "e")]
    RMS.Server.BL.PaymentBL[] RevenueReport();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/RevenueReportRespons" +
        "e")]
    System.Threading.Tasks.Task<RMS.Server.BL.PaymentBL[]> RevenueReportAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllClosedOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllClosedOrderRes" +
        "ponse")]
    RMS.Server.BL.OrderBL[] GetAllClosedOrder(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllClosedOrder", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllClosedOrderRes" +
        "ponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetAllClosedOrderAsync(System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllFoodReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllFoodReportResp" +
        "onse")]
    RMS.Server.BL.FoodReportBL[] GetAllFoodReport(System.DateTime date, int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllFoodReport", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllFoodReportResp" +
        "onse")]
    System.Threading.Tasks.Task<RMS.Server.BL.FoodReportBL[]> GetAllFoodReportAsync(System.DateTime date, int idCategory);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableTable" +
        "s", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableTable" +
        "sResponse")]
    RMS.Server.BL.TableBL[] GetAllAvailableTables();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableTable" +
        "s", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAvailableTable" +
        "sResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.TableBL[]> GetAllAvailableTablesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAssistanceRequ" +
        "ests", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAssistanceRequ" +
        "estsResponse")]
    RMS.Server.BL.TableBL[] GetAllAssistanceRequests(int idEmp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAssistanceRequ" +
        "ests", ReplyAction="http://RMS.Server.ServiceModel.Service.BL/IRestaurantService/GetAllAssistanceRequ" +
        "estsResponse")]
    System.Threading.Tasks.Task<RMS.Server.BL.TableBL[]> GetAllAssistanceRequestsAsync(int idEmp);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRestaurantServiceChannel : IRestaurantService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RestaurantServiceClient : System.ServiceModel.ClientBase<IRestaurantService>, IRestaurantService
{
    
    public RestaurantServiceClient()
    {
    }
    
    public RestaurantServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RestaurantServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestaurantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RestaurantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int InsertCategory(string name)
    {
        return base.Channel.InsertCategory(name);
    }
    
    public System.Threading.Tasks.Task<int> InsertCategoryAsync(string name)
    {
        return base.Channel.InsertCategoryAsync(name);
    }
    
    public string GetCategoryName(int CategoryID)
    {
        return base.Channel.GetCategoryName(CategoryID);
    }
    
    public System.Threading.Tasks.Task<string> GetCategoryNameAsync(int CategoryID)
    {
        return base.Channel.GetCategoryNameAsync(CategoryID);
    }
    
    public bool UpdateCategoryName(int idCategory, string name)
    {
        return base.Channel.UpdateCategoryName(idCategory, name);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateCategoryNameAsync(int idCategory, string name)
    {
        return base.Channel.UpdateCategoryNameAsync(idCategory, name);
    }
    
    public bool DeleteCategory(int idCategory)
    {
        return base.Channel.DeleteCategory(idCategory);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(int idCategory)
    {
        return base.Channel.DeleteCategoryAsync(idCategory);
    }
    
    public int InsertCustomer(string name, System.DateTime bday, string phone, string email)
    {
        return base.Channel.InsertCustomer(name, bday, phone, email);
    }
    
    public System.Threading.Tasks.Task<int> InsertCustomerAsync(string name, System.DateTime bday, string phone, string email)
    {
        return base.Channel.InsertCustomerAsync(name, bday, phone, email);
    }
    
    public int InsertEmployee(string name, string password, string type)
    {
        return base.Channel.InsertEmployee(name, password, type);
    }
    
    public System.Threading.Tasks.Task<int> InsertEmployeeAsync(string name, string password, string type)
    {
        return base.Channel.InsertEmployeeAsync(name, password, type);
    }
    
    public bool EmployeeReset(string name, string new_password)
    {
        return base.Channel.EmployeeReset(name, new_password);
    }
    
    public System.Threading.Tasks.Task<bool> EmployeeResetAsync(string name, string new_password)
    {
        return base.Channel.EmployeeResetAsync(name, new_password);
    }
    
    public bool CustomerReset(string name, string new_phone)
    {
        return base.Channel.CustomerReset(name, new_phone);
    }
    
    public System.Threading.Tasks.Task<bool> CustomerResetAsync(string name, string new_phone)
    {
        return base.Channel.CustomerResetAsync(name, new_phone);
    }
    
    public RMS.Server.BL.CustomerBL CustomerPhoneLookup(string phone)
    {
        return base.Channel.CustomerPhoneLookup(phone);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerPhoneLookupAsync(string phone)
    {
        return base.Channel.CustomerPhoneLookupAsync(phone);
    }
    
    public RMS.Server.BL.CustomerBL CustomerEmailLookup(string email)
    {
        return base.Channel.CustomerEmailLookup(email);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.CustomerBL> CustomerEmailLookupAsync(string email)
    {
        return base.Channel.CustomerEmailLookupAsync(email);
    }
    
    public RMS.Server.BL.EmployeeBL EmployeeLookup(string name)
    {
        return base.Channel.EmployeeLookup(name);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.EmployeeBL> EmployeeLookupAsync(string name)
    {
        return base.Channel.EmployeeLookupAsync(name);
    }
    
    public int OrderCount()
    {
        return base.Channel.OrderCount();
    }
    
    public System.Threading.Tasks.Task<int> OrderCountAsync()
    {
        return base.Channel.OrderCountAsync();
    }
    
    public bool UpdateOrderStatus(int idOrder, int status)
    {
        return base.Channel.UpdateOrderStatus(idOrder, status);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateOrderStatusAsync(int idOrder, int status)
    {
        return base.Channel.UpdateOrderStatusAsync(idOrder, status);
    }
    
    public bool UpdateOrderTip(int idOrder, decimal tip)
    {
        return base.Channel.UpdateOrderTip(idOrder, tip);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateOrderTipAsync(int idOrder, decimal tip)
    {
        return base.Channel.UpdateOrderTipAsync(idOrder, tip);
    }
    
    public int SubmitOrder(RMS.Server.BL.OrderBL new_order)
    {
        return base.Channel.SubmitOrder(new_order);
    }
    
    public System.Threading.Tasks.Task<int> SubmitOrderAsync(RMS.Server.BL.OrderBL new_order)
    {
        return base.Channel.SubmitOrderAsync(new_order);
    }
    
    public int SubmitOrderItem(RMS.Server.BL.MenuOrderBL Item)
    {
        return base.Channel.SubmitOrderItem(Item);
    }
    
    public System.Threading.Tasks.Task<int> SubmitOrderItemAsync(RMS.Server.BL.MenuOrderBL Item)
    {
        return base.Channel.SubmitOrderItemAsync(Item);
    }
    
    public RMS.Server.BL.OrderBL RetrieveOrder(int idTable)
    {
        return base.Channel.RetrieveOrder(idTable);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.OrderBL> RetrieveOrderAsync(int idTable)
    {
        return base.Channel.RetrieveOrderAsync(idTable);
    }
    
    public RMS.Server.BL.MenuOrderBL[] RetrieveOrderItems(int Order)
    {
        return base.Channel.RetrieveOrderItems(Order);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> RetrieveOrderItemsAsync(int Order)
    {
        return base.Channel.RetrieveOrderItemsAsync(Order);
    }
    
    public bool ClaimItem(int Item)
    {
        return base.Channel.ClaimItem(Item);
    }
    
    public System.Threading.Tasks.Task<bool> ClaimItemAsync(int Item)
    {
        return base.Channel.ClaimItemAsync(Item);
    }
    
    public RMS.Server.BL.OrderBL[] GetOrderByTableId(int tableId)
    {
        return base.Channel.GetOrderByTableId(tableId);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetOrderByTableIdAsync(int tableId)
    {
        return base.Channel.GetOrderByTableIdAsync(tableId);
    }
    
    public RMS.Server.BL.OrderBL[] GetAllAvailableOrdersForKitchen()
    {
        return base.Channel.GetAllAvailableOrdersForKitchen();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetAllAvailableOrdersForKitchenAsync()
    {
        return base.Channel.GetAllAvailableOrdersForKitchenAsync();
    }
    
    public RMS.Server.BL.OrderBL[] GetAllOrderTableStatus()
    {
        return base.Channel.GetAllOrderTableStatus();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetAllOrderTableStatusAsync()
    {
        return base.Channel.GetAllOrderTableStatusAsync();
    }
    
    public RMS.Server.BL.MenuOrderBL[] GetAllMenuOrderForOrder(int orderId)
    {
        return base.Channel.GetAllMenuOrderForOrder(orderId);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> GetAllMenuOrderForOrderAsync(int orderId)
    {
        return base.Channel.GetAllMenuOrderForOrderAsync(orderId);
    }
    
    public RMS.Server.BL.MenuOrderBL[] GetAllMenuOrderForKitchen(int orderId)
    {
        return base.Channel.GetAllMenuOrderForKitchen(orderId);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuOrderBL[]> GetAllMenuOrderForKitchenAsync(int orderId)
    {
        return base.Channel.GetAllMenuOrderForKitchenAsync(orderId);
    }
    
    public bool UpdateOrderMenuStatus(int menuOrderId, string status)
    {
        return base.Channel.UpdateOrderMenuStatus(menuOrderId, status);
    }
    
    public System.Threading.Tasks.Task<bool> UpdateOrderMenuStatusAsync(int menuOrderId, string status)
    {
        return base.Channel.UpdateOrderMenuStatusAsync(menuOrderId, status);
    }
    
    public bool ReadyItem(int Item)
    {
        return base.Channel.ReadyItem(Item);
    }
    
    public System.Threading.Tasks.Task<bool> ReadyItemAsync(int Item)
    {
        return base.Channel.ReadyItemAsync(Item);
    }
    
    public bool RequestAssistance(int table, string AssistType)
    {
        return base.Channel.RequestAssistance(table, AssistType);
    }
    
    public System.Threading.Tasks.Task<bool> RequestAssistanceAsync(int table, string AssistType)
    {
        return base.Channel.RequestAssistanceAsync(table, AssistType);
    }
    
    public RMS.Server.BL.CategoryBL[] GetAllCategory()
    {
        return base.Channel.GetAllCategory();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.CategoryBL[]> GetAllCategoryAsync()
    {
        return base.Channel.GetAllCategoryAsync();
    }
    
    public RMS.Server.BL.MenuItemBL[] GetAllMenuItem()
    {
        return base.Channel.GetAllMenuItem();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> GetAllMenuItemAsync()
    {
        return base.Channel.GetAllMenuItemAsync();
    }
    
    public RMS.Server.BL.MenuItemBL[] CategoryRetrieve(int idCategory)
    {
        return base.Channel.CategoryRetrieve(idCategory);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> CategoryRetrieveAsync(int idCategory)
    {
        return base.Channel.CategoryRetrieveAsync(idCategory);
    }
    
    public RMS.Server.BL.MenuItemBL[] GetAvailableMenuItems(int idCategory)
    {
        return base.Channel.GetAvailableMenuItems(idCategory);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> GetAvailableMenuItemsAsync(int idCategory)
    {
        return base.Channel.GetAvailableMenuItemsAsync(idCategory);
    }
    
    public double PriceLookup(int idItem)
    {
        return base.Channel.PriceLookup(idItem);
    }
    
    public System.Threading.Tasks.Task<double> PriceLookupAsync(int idItem)
    {
        return base.Channel.PriceLookupAsync(idItem);
    }
    
    public RMS.Server.BL.MenuItemBL ItemLookup(int idItem)
    {
        return base.Channel.ItemLookup(idItem);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL> ItemLookupAsync(int idItem)
    {
        return base.Channel.ItemLookupAsync(idItem);
    }
    
    public bool ActivateItem(RMS.Server.BL.MenuItemBL alive)
    {
        return base.Channel.ActivateItem(alive);
    }
    
    public System.Threading.Tasks.Task<bool> ActivateItemAsync(RMS.Server.BL.MenuItemBL alive)
    {
        return base.Channel.ActivateItemAsync(alive);
    }
    
    public bool DeactivateItem(RMS.Server.BL.MenuItemBL dead)
    {
        return base.Channel.DeactivateItem(dead);
    }
    
    public System.Threading.Tasks.Task<bool> DeactivateItemAsync(RMS.Server.BL.MenuItemBL dead)
    {
        return base.Channel.DeactivateItemAsync(dead);
    }
    
    public RMS.Server.BL.CompBL CompLookup(int idMenuOrder)
    {
        return base.Channel.CompLookup(idMenuOrder);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.CompBL> CompLookupAsync(int idMenuOrder)
    {
        return base.Channel.CompLookupAsync(idMenuOrder);
    }
    
    public int CompItem(RMS.Server.BL.CompBL newComp)
    {
        return base.Channel.CompItem(newComp);
    }
    
    public System.Threading.Tasks.Task<int> CompItemAsync(RMS.Server.BL.CompBL newComp)
    {
        return base.Channel.CompItemAsync(newComp);
    }
    
    public bool updateComp(int idMenuOrder, int idComp)
    {
        return base.Channel.updateComp(idMenuOrder, idComp);
    }
    
    public System.Threading.Tasks.Task<bool> updateCompAsync(int idMenuOrder, int idComp)
    {
        return base.Channel.updateCompAsync(idMenuOrder, idComp);
    }
    
    public int Payment(int idOrder, string method, double amount, int userID)
    {
        return base.Channel.Payment(idOrder, method, amount, userID);
    }
    
    public System.Threading.Tasks.Task<int> PaymentAsync(int idOrder, string method, double amount, int userID)
    {
        return base.Channel.PaymentAsync(idOrder, method, amount, userID);
    }
    
    public RMS.Server.BL.CompBL[] DiscountReport()
    {
        return base.Channel.DiscountReport();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.CompBL[]> DiscountReportAsync()
    {
        return base.Channel.DiscountReportAsync();
    }
    
    public RMS.Server.BL.MenuItemBL[] Top3Report()
    {
        return base.Channel.Top3Report();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.MenuItemBL[]> Top3ReportAsync()
    {
        return base.Channel.Top3ReportAsync();
    }
    
    public RMS.Server.BL.PaymentBL[] RevenueReport()
    {
        return base.Channel.RevenueReport();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.PaymentBL[]> RevenueReportAsync()
    {
        return base.Channel.RevenueReportAsync();
    }
    
    public RMS.Server.BL.OrderBL[] GetAllClosedOrder(System.DateTime date)
    {
        return base.Channel.GetAllClosedOrder(date);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.OrderBL[]> GetAllClosedOrderAsync(System.DateTime date)
    {
        return base.Channel.GetAllClosedOrderAsync(date);
    }
    
    public RMS.Server.BL.FoodReportBL[] GetAllFoodReport(System.DateTime date, int idCategory)
    {
        return base.Channel.GetAllFoodReport(date, idCategory);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.FoodReportBL[]> GetAllFoodReportAsync(System.DateTime date, int idCategory)
    {
        return base.Channel.GetAllFoodReportAsync(date, idCategory);
    }
    
    public RMS.Server.BL.TableBL[] GetAllAvailableTables()
    {
        return base.Channel.GetAllAvailableTables();
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.TableBL[]> GetAllAvailableTablesAsync()
    {
        return base.Channel.GetAllAvailableTablesAsync();
    }
    
    public RMS.Server.BL.TableBL[] GetAllAssistanceRequests(int idEmp)
    {
        return base.Channel.GetAllAssistanceRequests(idEmp);
    }
    
    public System.Threading.Tasks.Task<RMS.Server.BL.TableBL[]> GetAllAssistanceRequestsAsync(int idEmp)
    {
        return base.Channel.GetAllAssistanceRequestsAsync(idEmp);
    }
}
